dist: trusty

sudo: required

language: generic

env:
  global:
    - TIMEOUT=30

cache:
  - apt

matrix:
  include:
    - os: linux
      env:
        - BUILD_NAME=XENIAL_DEBUG
        - DOCKER_FILE="ubuntu-xenial"
        - BUILD_TYPE=Debug
        - CATKIN_CONFIG_OPTIONS="-DCMAKE_BUILD_TYPE=Debug"
      services: docker
    - os: linux
      env:
        - BUILD_NAME=XENIAL_RELEASE
        - DOCKER_FILE="ubuntu-xenial"
        - BUILD_TYPE=Release
        - CATKIN_CONFIG_OPTIONS="-DCMAKE_BUILD_TYPE=Release"
      services: docker

before_install:
  - if [ -n "$DOCKER_FILE" ]; then
      docker build -t "$DOCKER_FILE" -f ".ci/docker/$DOCKER_FILE" .;
      docker run -itd -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR --env-file .ci/docker/env.list --name my-docker "$DOCKER_FILE";
      docker exec my-docker /bin/sh -c "cd $TRAVIS_BUILD_DIR && ./.ci/before_install.sh";
    else
      '.ci/before_install.sh';
    fi

install:
  - if [ -n "$DOCKER_FILE" ]; then
      docker exec my-docker /bin/sh -c "cd $TRAVIS_BUILD_DIR && ./.ci/install.sh";
    else
      '.ci/install.sh';
    fi

script:
  - if [ -n "$DOCKER_FILE" ]; then
      docker exec my-docker /bin/sh -c "cd $TRAVIS_BUILD_DIR && ./.ci/script.sh";
    else
      '.ci/script.sh';
    fi
